server:
  port: 8000
spring:
  application:
    name: spring-cloud-eureka
  security:
    user:
      name: ngcly
      password: 123456
  boot:
    admin:
      client:
        url: http://localhost:8081
  zipkin:
    base-url: http://localhost:8082
  profiles:

eureka:
  client:
    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: false # 是否拉取其它服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://localhost:${server.port}/eureka